## The functions below deal with matrix inversion. The result of
## the matrix inversion is stored in cache so that it can be
## called later.



## makeCacheMatrix creates an object with a list of functions that
## set the value of the matrix
## get the value of the matrix
## set the value of the solve
## get the value of the solve

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function()x
        setsolve <- function(solve) m <<- solve
        #gets the stored inverse matrix
        getsolve <- function() m
        list(set = set, get = get,
             setsolve = setsolve
             getsolve = getsolve)
}


## cacheSolve takes a list generated by calling to the function above
## (makeCacheMatrix) and retuns the inverse matrix. If the inverse
## has not yet been calculated it will perform the calculation. If the
## inverse has been called it will return the stored value.

cacheSolve <- function(x, ...) {
        m <- x$getsolve()
        if(!is.null(m)) {
                message("getting inverse matrix from cached data")
                return(m)
        }
        data <- x$get()
        message("")
        m <- solve(data, ...)
        x$setsolve(m)
        ## retrun inverse matrix
        m
}
